### ISSUE TITLE
result of rayTest

### ISSUE THREAD

**Issue by HelloWorldlsla** [jMonkeyEngine/jmonkeyengine#1027]
Hello

Can someone make a quick change?
I'm talking about the function rayTest() and rayTestRaw() of the class [PhysicsSpace](https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-bullet/src/main/java/com/jme3/bullet/PhysicsSpace.java).

Instead of returning a simple List, I suggest to return a List of PhysicsRayTestResult.
Look like this:

`public List<PhysicsRayTestResult> rayTest() {}`
instead of this:
`public List rayTest() {}`

And the same for the rayTestRaw method:
`public List<PhysicsRayTestResult> rayTestRaw() {}`
instead of this:
`public List rayTest() {}`

Why?
Beacause in IntelliJ IDEA (I don't know how it looks in other IDEs) casting
 a `List` to a `List<PhysicsRayTestResult>` make the line colored yellow.
And guys like me don't like colored lines...

Regards

**Comment by stephengold** [comment]
This issue exists only with `jme3-bullet` library. In `jme3-jbullet`, the return type is more precise.

**Comment by stephengold** [comment]
Fixed in `master` branch at 15f9f69611fb429ef9fc6e1261e0071e0cccddd7 .

**Comment by HelloWorldlsla** [comment]
Hi [stephengold](/stephengold)
Thanks for this update, but....
I think you forgot to change the result of the `rayTestRaw()`method :)

Have a good day!

**Comment by stephengold** [comment]
You're right! I think the fix is now complete.
